meta:
  title: Redocly Training
  description: The best API documentation generator ever.
  siteUrl: https://developer-portal-starter.redoc.ly
  keywords: redocly developer portal, api portal starter, api reference docs
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo:
  image: ./images/logo.svg
  altText: Redocly Training
login:
  label: Sign in
  userAvatar:
    claim: picture
    fallbackLettersClaim: fullName
  userLabel: false
  menu:
    - label: Profile
      page: profile.mdx
    - separatorLine: true
    - label: Sign out
      logout: true
      link: "https://your_domain/v2/logout?client_id=YOUR_CLIENT_ID&returnTo=LOGOUT_URL"
toc:
  enable: true
oasDefinitions:
  petstore: ./openapi/petstore.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
  - "./static/fonts.css"
#analytics:
# ga:
# note that GA doesn't work in the development environment
#  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:
  - label: Training exercises
    page: developer-portal/index.md

  - label: External docs
    icon: ./images/redocly-icon-white.png
    href: https://test-canoo.redoc.ly/

  - search: true

footer:
  copyrightText: Copyright © Redocly 2019-2021. All right reserved.
  columns:
    - group: Legal
      items:
        - label: Terms of Use
          href: "https://redoc.ly/subscription-agreement/"
        - label: Privacy Notice
          href: "https://redoc.ly/privacy-notice/"
        - label: Cookie Notice
          href: "https://redoc.ly/cookie-notice/"
    - group: Support
      items:
        - label: FAQ
          page: faq.md
        - label: Contact us
          page: contact.mdx
